spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-hirisun-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-hirisun-test